all:
	cd $(WORK_ROOT)/src/simple_uv && make clean && make
	cd $(WORK_ROOT)/src/uvtest && make clean && make
	cd $(WORK_ROOT)/src/testclient && make clean && make
	

clean:
	cd $(WORK_ROOT)/src/simple_uv && make clean
	cd $(WORK_ROOT)/src/uvtest && make clean
	cd $(WORK_ROOT)/src/testclient && make clean
